// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type Article struct {
	ID             interface{}
	FetchedAt      time.Time
	ArticleUrl     string
	ArticleTitle   string
	ArticleSummary string
	ArticleAuthors string
	SearchID       interface{}
}

type Candidate struct {
	ID          interface{}
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        string
	LinkedinUrl sql.NullString
	GithubUrl   sql.NullString
}

type CandidateArticle struct {
	ID          interface{}
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CandidateID interface{}
	ArticleID   interface{}
}

type CandidateCategory struct {
	ID            interface{}
	CreatedAt     time.Time
	UpdatedAt     time.Time
	CandidateID   interface{}
	ArxivCategory string
}

type CandidateSearch struct {
	ID             interface{}
	CreatedAt      time.Time
	UpdatedAt      time.Time
	CandidateID    interface{}
	SearchID       interface{}
	RelevanceScore sql.NullFloat64
	Notes          sql.NullString
}

type Search struct {
	ID              interface{}
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Description     string
	ArvixUrl        string
	ResultsPerFetch sql.NullInt64
	LastFetchDate   sql.NullTime
}
